concert_chute_django/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('view_venue/<str:pk>/', views.view_venue, name='view_venue'),
]

concert_chute_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('concert_chute_django.core.urls')),
]

concert_chute_django/core/models.py
from django.db import models


class Concert(models.Model):
    eventful_id = models.CharField(max_length=100, primary_key=True)
    title = models.TextField(null=True)
    description = models.TextField(null=True)
    url = models.URLField(max_length=500, null=True)
    start_time = models.DateTimeField()
    recur_string = models.CharField(max_length=500, null=True)

    venue = models.ForeignKey('Venue', on_delete=models.CASCADE)

    class Meta:
        ordering = ['start_time']


class Venue(models.Model):
    eventful_id = models.CharField(max_length=100, primary_key=True)
    name = models.CharField(max_length=1000, null=True)
    url = models.URLField(max_length=1000, null=True)
    city = models.CharField(max_length=400, null=True)
    country = models.CharField(max_length=400, null=True)
    region = models.CharField(max_length=400, null=True)
    address = models.TextField(null=True)

concert_chute_django/core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from concert_chute_django.core.models import Concert, Venue
from concert_chute_django.core.utils import upcoming_concerts


# Create your views here.
def home(request):
    return render(request, 'home.html', {'concerts': upcoming_concerts()})


def view_venue(request, pk):
    return render(request, 'view_venue.html', {
        'venue': get_object_or_404(Venue, pk=pk)
    })

concert_chute_django/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<title>
	    ConcertChute | {% block title %}{% endblock title %}
	</title>
    </head>

    <body>
	<div class="header">
	    <h1><a href="{% url 'home' %}">ConcertChute</a> Washington, DC</h1>
	    <div id="credit">
		<a href="https://zullo.dev">
		    a <strong>ZULLO.DEV</strong> site
		</a>
	    </div>
	</div>
	{% block content %}
	{% endblock content %}
    </body>
</html>

concert_chute_django/core/templates/home.html
{% extends 'base.html' %}

{% block title %}Upcoming Shows in Washington, DC{% endblock title %}

{% block content %}
    <table>
	<tr>
	    <th>Venue</th>
	    <th>Title</th>
	    <th>Start Time</th>
	</tr>
	{% for concert in concerts %}
	    <tr>
		<td><a href="{% url 'view_venue' concert.venue.pk %}">{{ concert.venue.name }}</a></td>
		<td>{{ concert.title|truncatechars:100 }}</td>
		<td nowrap>{{ concert.start_time|date:"D, M d h:i A" }}</td>
	    </tr>
	{% endfor %}
    </table>
{% endblock content %}

concert_chute_django/core/templates/view_venue.html
{% extends 'base.html' %}

{% block title %}Venue: {{ venue.name }}{% endblock title %}

{% block content %}
    <h2>{{ venue.name }}</h2>
    <a href="{{ venue.url }}">Eventful Link</a>

    <table>
	<tr>
	    <th>Title</th>
	    <th>Start Time</th>
	</tr>
	{% for concert in venue.concert_set.all %}
	    <tr>
		<td>{{ concert.title }}</td>
		<td>{{ concert.start_time }}</td>
	    </tr>
	{% endfor %}
    </table>
{% endblock content %}